# https://github.com/svenfuchs/rails-i18n/blob/master/rails/locale/en-US.yml
en:

  # = start data_types =========================================================

  # == date ====================================================================
  date:
    abbr_day_names:
    - Sun
    - Mon
    - Tue
    - Wed
    - Thu
    - Fri
    - Sat
    abbr_month_names:
    - 
    - Jan
    - Feb
    - Mar
    - Apr
    - May
    - Jun
    - Jul
    - Aug
    - Sep
    - Oct
    - Nov
    - Dec
    day_names:
    - Sunday
    - Monday
    - Tuesday
    - Wednesday
    - Thursday
    - Friday
    - Saturday
    formats:
      default: "%m-%d-%Y"
      long: "%B %d, %Y"
      short: "%b %d"
    month_names:
    - 
    - January
    - February
    - March
    - April
    - May
    - June
    - July
    - August
    - September
    - October
    - November
    - December
    order:
    - :month
    - :day
    - :year

  # == datetime ================================================================
  datetime:
    distance_in_words:
      about_x_hours:
        one: about 1 hour
        other: about %{count} hours
      about_x_months:
        one: about 1 month
        other: about %{count} months
      about_x_years:
        one: about 1 year
        other: about %{count} years
      almost_x_years:
        one: almost 1 year
        other: almost %{count} years
      half_a_minute: half a minute
      less_than_x_seconds:
        one: less than 1 second
        other: less than %{count} seconds
      less_than_x_minutes:
        one: less than a minute
        other: less than %{count} minutes
      over_x_years:
        one: over 1 year
        other: over %{count} years
      x_seconds:
        one: 1 second
        other: "%{count} seconds"
      x_minutes:
        one: 1 minute
        other: "%{count} minutes"
      x_days:
        one: 1 day
        other: "%{count} days"
      x_months:
        one: 1 month
        other: "%{count} months"
      x_years:
        one: 1 year
        other: "%{count} years"
    prompts:
      second: Second
      minute: Minute
      hour: Hour
      day: Day
      month: Month
      year: Year

  # == number ==================================================================
  number:
    currency:
      format:
        delimiter: ","
        format: "%u%n"
        precision: 2
        separator: "."
        significant: false
        strip_insignificant_zeros: false
        unit: "$"
        #unit: "" #Customized
    format:
      delimiter: ","
      precision: 3
      separator: "."
      significant: false
      strip_insignificant_zeros: false
    human:
      decimal_units:
        format: "%n %u"
        units:
          billion: Billion
          million: Million
          quadrillion: Quadrillion
          thousand: Thousand
          trillion: Trillion
          unit: ''
      format:
        delimiter: ''
        precision: 3
        significant: true
        strip_insignificant_zeros: true
      storage_units:
        format: "%n %u"
        units:
          byte:
            one: Byte
            other: Bytes
          eb: EB
          gb: GB
          kb: KB
          mb: MB
          pb: PB
          tb: TB
    percentage:
      format:
        delimiter: ''
        format: "%n%"
    precision:
      format:
        delimiter: ''
  support:
    array:
      last_word_connector: ", and "
      two_words_connector: " and "
      words_connector: ", "
  time:
    am: am
    formats:
      default: "%a, %d %b %Y %I:%M:%S %p %Z"
      long: "%B %d, %Y %I:%M %p"
      long_phrase: "%A %d %^B %Y at %H:%M and %S seconds" #customized
      short: "%d %b %I:%M %p"
      short_phrase: "The day %d %^B %Y" #customized
    pm: pm

  # = end data_types =========================================================

  # == errors ==================================================================
  errors:
    format: "%{attribute} %{message}"
    messages:
      accepted: must be accepted
      blank: can't be blank
      confirmation: doesn't match %{attribute}
      empty: can't be empty
      equal_to: must be equal to %{count}
      even: must be even
      exclusion: is reserved
      greater_than: must be greater than %{count}
      greater_than_or_equal_to: must be greater than or equal to %{count}
      inclusion: is not included in the list
      invalid: is invalid
      less_than: must be less than %{count}
      less_than_or_equal_to: must be less than or equal to %{count}
      model_invalid: 'Validation failed: %{errors}'
      not_a_number: is not a number
      not_an_integer: must be an integer
      odd: must be odd
      other_than: must be other than %{count}
      present: must be blank
      required: must exist
      taken: has already been taken
      too_long:
        one: is too long (maximum is 1 character)
        other: is too long (maximum is %{count} characters)
      too_short:
        one: is too short (minimum is 1 character)
        other: is too short (minimum is %{count} characters)
      wrong_length:
        one: is the wrong length (should be 1 character)
        other: is the wrong length (should be %{count} characters)
    template:
      body: 'There were problems with the following fields:'
      header:
        one: 1 error prohibited this %{model} from being saved
        other: "%{count} errors prohibited this %{model} from being saved"

  # == form_errors_message =====================================================
  form_errors_message:
    one: "1 error prevented saving"
    other: "%{count} errors prevented saving"

  # == helpers ==================================================================
  helpers:
    select:
      prompt: Please select
    submit:
      create: Create %{model}
      submit: Save %{model}
      update: Update %{model}
      # user:
      #   create: "Create %{model}"
      #   update: "Update %{model}"
      # eg_company:
      #   create: "Crete %{model}"
      #   update: "Update %{model}"
    label:
      user:
        name: "User name"
        email: "email"
        password: "password"
        password_confirmation: "password confirmation"
    placeholder:
      user:
        name: "user name"
        email: "email"
        password: "password"
        password_confirmation: "password confirmation"

  # == activerecord ============================================================
  activerecord:
    errors:
      messages:
        record_invalid: 'Validation failed: %{errors}'
        restrict_dependent_destroy:
          has_one: Cannot delete record because a dependent %{record} exists
          has_many: Cannot delete record because dependent %{record} exist
      models:
        user:
          attributes:
            name:
              blank: ": required field"
            email:
              blank: ": required field"
              invalid: ": not valid"
            password:
              blank: ": required field"
              too_short: ": too short"
            password_confirmation:
              confirmation: ": does not match with password"
    attributes:
      company:
        address: "Address"
        building: "Building"
        client_rate: "Client rate"
        client_type: "client's typology"
        name: "Name"
        note: "Note"
        tax_number_1: "VAT number"
        tax_number_2: "taxation id number"
        sector: "Sector"
        supplier_rate: "Supplier rate"
        supplier_type: "Supplier's typology"
      company/client_type:
        c_none: "none" 
        c_goods: "goods" 
        c_services: "services"
        c_goods_and_services: "goods and services"
      company/supplier_type:
        s_none: "none" 
        s_goods: "goods" 
        s_services: "services"
        s_goods_and_services: "goods and services"
      person:
        title: "Title"
        first_name: "Name"
        last_name: "Surname"
        homonym: "Homonym"
        note: "Note"
      user:
        name: "User name" # fallback for when label is nil
        email: "email"
        password: "password"
        password_confirmation: "Password confirmation"
    models:
      company: "company"
      eg_company: "example company"
      user: "user"

  # = start views ==============================================================

  companies:
    index:
      html_head_title: "All companies"
      form_search_placeholder: "find company ..."

  company_person_maps:
    index:
      html_head_title: "Companies -> People"
    form_search:
      company: "Company"
      person: "Person"
      form_search_placeholder: "find ..."
      submit: "search"

  eg_companies:
    index:
      html_head_title: "All companies"
    show:
      html_head_title: "Company"
    edit:
      html_head_title: "Edit"
    new:
      html_head_title: "New company"

  eg_components:
    index:
      html_head_title: "All components"
    show:
      html_head_title: "Comp."
    edit:
      html_head_title: "Edit"
    new:
      html_head_title: "New component"

  eg_posts:
    not_published: "It is not published yet"
    index:
      html_head_title: "All the posts"
    show:
      welcome: "Welcome, %{name}"
      html_head_title: "Art."
      price_fomatted: "This cost %{price} of money"
    edit:
      html_head_title: "Edit"
    new:
      html_head_title: "New post"

  mockups:
    page_a:
      headline: "This is the homepage"
      first_paragraph: "the text showed here is passed via a 'translation file' and this means that our application is ready to support more languages."
      link_to_page_B: "Let's go to page B."

  pages:
    home:
      html_head_title: "homepage"
      last_access: "Last Access"
      role: "Role"
      italian: "Italian"
      english: "English"
      select_item: "Select item..."
      company: "Company"
      person: "Person"
      previous: "Prev."
      of: "of"
      next: "Next"
      dismiss: "Dismiss"
      find: "Find..."
      more_used_items: "The more used items"
      no_user_logged: "No user logged in"
      
  users:
    index:
      html_head_title: "All users"
    new:
      html_head_title: "New user"
    edit:
      html_head_title: "Edit"
    create:
      notice: "The user was created successfully."
    update:
      notice: "The user was successfully updated."

  # = end views ================================================================

  # == Generic Vocablulary =====================================================
  vocabolary:
    ball: "ball"
    dog: "dog"