it:
  activerecord:
    attributes:
      user:
        name: "Nome utente" # fallback for when label is nil
        email: "email"
        password: "password"
        password_confirmation: "conferma password"
    models:
      user: "utente"
      eg_company: "azienda esempio"
    errors:
      models:
        user:
          attributes:
            name:
              blank: ": campo obbligatorio"
            email:
              blank: ": campo obbligatorio"
              invalid: ": non valida"
            password:
              blank: ": campo obbligatorio"
              too_short: ": troppo corta"
            password_confirmation:
              confirmation: ": non corrisponde con password"

  form_errors_message:
    one: "1 errore ha impedito il salvataggio"
    other: "%{count} errori hanno impedito il salvataggio"

  helpers:
    label:
      user:
        name: "Nome utente"
        email: "email"
        password: "password"
        password_confirmation: "conferma password"
    placeholder:
      user:
        name: "nome utente"
        email: "email"
        password: "password"
        password_confirmation: "conferma password"
    submit:
      user:
        create: "Crea %{model}"
        update: "Aggiorna %{model}"
      eg_company:
        create: "Crea %{model}"
        update: "Aggiorna %{model}"

  # Controllers ----------------------------------------------------------------

  eg_companies:
    index:
      html_head_title: "Tutte le aziende"
    show:
      html_head_title: "Az."
    edit:
      html_head_title: "Modifica"
    new:
      html_head_title: "Nuova azienda"

  eg_components:
    index:
      html_head_title: "Tutti i componenti"
    show:
      html_head_title: "Comp."
    edit:
      html_head_title: "Modifica"
    new:
      html_head_title: "Nuovo componente"

  eg_posts:
    index:
      html_head_title: "Tutti gli articoli"
    show:
      html_head_title: "Art."
    edit:
      html_head_title: "Modifica"
    new:
      html_head_title: "Nuovo articolo"
  
  mockups:
    page_a:
      headline: "Questa è l'homepage"
      first_paragraph: "il testo mostrato è o passato da un 'file di traduzione' e questo significa che la nostra applicazione è pronta a supportare più lingue."
      link_to_page_B: "Andiamo alla pagina B"

  users:
    index:
      html_head_title: "Tutti gli utenti"
    new:
      html_head_title: "Nuovo utente"
    edit:
      html_head_title: "Modifica"
    create:
      notice: "L'utente è stato creato con successo."
    update:
      notice: "L'utente è stato aggiornato con successo."
